<a href="https://colab.research.google.com/github/matosdacostaeduardo9-debug/1-fundamentos-digitais/blob/main/aula%20pratica%20linguagem%20de%20programa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - 1º Abrir a documentação

# NUMPY - 2º Qual a diferença do array NUMPAY para list in python

In [57]:
num_elementos = 10000000
import numpy as np
# lista_elementos = []
# for x in range(num_elementos):
#     lista_elementos.append(x)
# print(lista_elementos[-1])
array_elementos = np.arange(num_elementos)
print(array_elementos[-1])

9999999


# Numpy - 3º Criação de arryas em numpy


In [59]:
import numpy as np


print(f'Criação de array numpy utilizando o método .arange:\n{np.arange(10)}\n')
print(f'Criação de array numpy utilizando o método .array:\n{np.array([0,1,2,3,4,5,6,7,8,9])}\n')
print(f'Criação de array numpy utilizando o método .ones:\n{np.ones([100])}\n')
print(f'Criação de array numpy utilizando o método .empty:\n{np.empty(12)}\n')
print(f'Criação de array numpy utilizando o método .arange:\n{np.arange(101)}\n')
print(f'Criação de array numpy utilizando o método .linspace:\n{np.linspace(0,100,num = 101)}\n')

Criação de array numpy utilizando o método .arange:
[0 1 2 3 4 5 6 7 8 9]

Criação de array numpy utilizando o método .array:
[0 1 2 3 4 5 6 7 8 9]

Criação de array numpy utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]

Criação de array numpy utilizando o método .empty:
[3.92103484e-315 0.00000000e+000 2.10077583e-312 6.79038654e-313
 2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313
 2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]

Criação de array numpy utilizando o método .arange:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47

# NUMPY - 4º A importância de se defenir o tipo de dado

In [60]:
import numpy as np

num_elementos = 1000000000
array_performace = np.zeros(num_elementos, dtype = np.int32)

# NUMPY - 5º Criação de números randômicos

In [61]:
import numpy as np

rng = np.random.default_rng()
print(rng.random(10))

[0.83187215 0.84842095 0.31018071 0.40329304 0.59329632 0.14128088
 0.83116355 0.65614147 0.9817849  0.29774869]


# NUMPY - 6º Vetor, Matriz, tensor

In [62]:
import numpy as np

rng = np.random.default_rng()
vetor = rng.random(4)
print(f'Array de 1 Dimensão (VETOR) randômico:\n{vetor}\n')
matriz = rng.random([4,4])
print(f'Array de 2 Dimensão (MATRIZ) randômico:\n{matriz}\n')
tensor = rng.random([4,4,4,4])
print(f'Array de 3 Dimensão (TENSOR) randômico:\n{tensor}\n')

Array de 1 Dimensão (VETOR) randômico:
[0.44149518 0.28820393 0.98807884 0.0847041 ]

Array de 2 Dimensão (MATRIZ) randômico:
[[0.79910261 0.76068902 0.27593856 0.57661906]
 [0.93519917 0.6173316  0.1746778  0.77891936]
 [0.63455449 0.82195687 0.83927714 0.89689694]
 [0.03827373 0.14100715 0.73486922 0.39537389]]

Array de 3 Dimensão (TENSOR) randômico:
[[[[0.9292043  0.20010263 0.63081033 0.03136555]
   [0.23646259 0.0528402  0.08476498 0.00683135]
   [0.3551736  0.02663793 0.84324914 0.89327448]
   [0.27372531 0.51622487 0.18636075 0.85086526]]

  [[0.03255715 0.15104947 0.60498281 0.96415944]
   [0.89340398 0.71470016 0.76335067 0.10212703]
   [0.20188387 0.03451567 0.32262166 0.13660916]
   [0.82114501 0.75536594 0.25930016 0.37464272]]

  [[0.22659816 0.34033047 0.40767903 0.14742126]
   [0.24171252 0.42604122 0.17000852 0.72470384]
   [0.97443345 0.2630314  0.25712284 0.16803774]
   [0.6964183  0.98182477 0.95197576 0.48659429]]

  [[0.97599915 0.0180707  0.1021718  0.74003548]
 

# NUMPY - 7º Ordenação e Adicionar Elementos

In [63]:
import numpy as np

rng = np.random.default_rng()

array_1= rng.random([2,3])
print(f'Array 1 Sem ordenação:\n{array_1}\n')
print(f'Array 1 Sem ordenação:\n{np.sort(array_1, axis = 0)}\n')

# Concatenação

array_2 = rng.random([2,1])
print(f'Array 2:\n{array_2}\n')

Array_concatenado = np.concatenate([array_1,array_2], axis=1)
print(f'Array Concatenado:\n{Array_concatenado}\n')

array_concatenado_2 = np.hstack([array_1,array_2])
print(f'Array Concatenado:\n{array_concatenado_2}\n')

Array 1 Sem ordenação:
[[0.84432773 0.41727958 0.70182983]
 [0.37877308 0.42725981 0.69471202]]

Array 1 Sem ordenação:
[[0.37877308 0.41727958 0.69471202]
 [0.84432773 0.42725981 0.70182983]]

Array 2:
[[0.99500375]
 [0.01628686]]

Array Concatenado:
[[0.84432773 0.41727958 0.70182983 0.99500375]
 [0.37877308 0.42725981 0.69471202 0.01628686]]

Array Concatenado:
[[0.84432773 0.41727958 0.70182983 0.99500375]
 [0.37877308 0.42725981 0.69471202 0.01628686]]



# NUMPY - 8º Conhecendo o seu Array

In [115]:
import numpy as np

rng = np.random.default_rng()
array_teste_4 = rng.random([23,43,17])
print(array_teste_4)

print(f'Quais são as suas dimensões:\n{array_teste_4.ndim}\n')
print(f'Quais o seu formato:\n{array_teste_4.shape}\n')
print(f'Quantos elementos possui:\n{array_teste_4.size}\n')

[[[0.81106777 0.10410998 0.55009219 ... 0.20014387 0.37550018 0.39625352]
  [0.80011005 0.45323034 0.21044693 ... 0.92862403 0.18609471 0.01216784]
  [0.32474648 0.98255964 0.29325407 ... 0.56011648 0.05687651 0.67225447]
  ...
  [0.62189769 0.12848525 0.42077151 ... 0.36619118 0.95821789 0.36804956]
  [0.0158854  0.11984989 0.67198415 ... 0.46732588 0.56204475 0.95736716]
  [0.28946448 0.63767782 0.34141955 ... 0.3146746  0.68743876 0.55602403]]

 [[0.06851601 0.93418654 0.22542282 ... 0.7763925  0.49268334 0.7942531 ]
  [0.84501773 0.81685062 0.54538393 ... 0.48716824 0.99127788 0.51163559]
  [0.17812886 0.88168838 0.36940438 ... 0.55815737 0.04188107 0.93900942]
  ...
  [0.00523622 0.89886834 0.07846981 ... 0.60058071 0.28011119 0.41525271]
  [0.78163273 0.98868769 0.06095342 ... 0.03297077 0.13055594 0.52354158]
  [0.19994969 0.6046312  0.54757963 ... 0.32212783 0.20867236 0.61610582]]

 [[0.43088618 0.78752847 0.00243992 ... 0.34149934 0.93621967 0.81541224]
  [0.05069032 0.592221

# NUMPY 9 - Como mudar o formato do array

In [93]:
import numpy as np

array_a = np.arange(1,20)
print(f'Array_a:\n{array_a}\n')
array_a = array_a.reshape(4,5)
print(f'Array_a:\n{array_a}\n')

array_a = np.reshape(array_a, [4,5])
print(f'Array_a:\n{array_a}\n')

array_a = array_a.flatten()
print(f'Array_a:\n{array_a}\n')

array_b = array_a.reshape(4,5)
print(f'Array_b:\n{array_b}\n')

array_b = np.vsplit(array_b,4)
print(f'Array_b:\n{array_b}\n')
print(array_b[0])

Array_a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array_a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array_a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array_a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array_b:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array_b:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]

[[0 1 2 3 4]]


# PLOTLY - 1º Abir Documentação

# PLOTLY - 2º Criando arrays pra montar

In [113]:
import numpy as np

a = 3/4
b = 2/4
c = 1/4
vetor_a = np.ones(20)
vetor_b = np.ones(20)
vetor_c = np.ones(20)

for i in range (1,20):
    vetor_a[i] = vetor_a[i -1] + a**i
    vetor_b[i] = vetor_b[i -1] + b**i
    vetor_c[i] = vetor_c[i -1] + c**i

print(vetor_a)
print(vetor_b)
print(vetor_c)

np.savetxt('vetor_a.txt', vetor_a, fmt='%f', delimiter= ';')
np.savetxt('vetor_b.txt', vetor_b, fmt='%f', delimiter= ';')
np.savetxt('vetor_c.txt', vetor_c, fmt='%f', delimiter= ';')

[1.         1.75       2.3125     2.734375   3.05078125 3.28808594
 3.46606445 3.59954834 3.69966125 3.77474594 3.83105946 3.87329459
 3.90497094 3.92872821 3.94654616 3.95990962 3.96993221 3.97744916
 3.98308687 3.98731515]
[1.         1.5        1.75       1.875      1.9375     1.96875
 1.984375   1.9921875  1.99609375 1.99804688 1.99902344 1.99951172
 1.99975586 1.99987793 1.99993896 1.99996948 1.99998474 1.99999237
 1.99999619 1.99999809]
[1.         1.25       1.3125     1.328125   1.33203125 1.33300781
 1.33325195 1.33331299 1.33332825 1.33333206 1.33333302 1.33333325
 1.33333331 1.33333333 1.33333333 1.33333333 1.33333333 1.33333333
 1.33333333 1.33333333]


# PLOTLY - 3º Criando nosso primeiro gráfico

In [114]:
import numpy as np
import plotly.express as px

array_a = np.loadtxt('vetor_a.txt', dtype = np.float64, delimiter=';')
array_b = np.loadtxt('vetor_b.txt', dtype = np.float64, delimiter=';')
array_c = np.loadtxt('vetor_c.txt', dtype = np.float64, delimiter=';')
print(array_a)


array_abc = np.vstack([array_a,array_b,array_c])
print(array_abc)
array_abc = array_abc.transpose()
print(array_abc)
fig = px.line(array_abc)
fig.show()

[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
 3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
 3.969932 3.977449 3.983087 3.987315]
[[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
  3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
  3.969932 3.977449 3.983087 3.987315]
 [1.       1.5      1.75     1.875    1.9375   1.96875  1.984375 1.992188
  1.996094 1.998047 1.999023 1.999512 1.999756 1.999878 1.999939 1.999969
  1.999985 1.999992 1.999996 1.999998]
 [1.       1.25     1.3125   1.328125 1.332031 1.333008 1.333252 1.333313
  1.333328 1.333332 1.333333 1.333333 1.333333 1.333333 1.333333 1.333333
  1.333333 1.333333 1.333333 1.333333]]
[[1.       1.       1.      ]
 [1.75     1.5      1.25    ]
 [2.3125   1.75     1.3125  ]
 [2.734375 1.875    1.328125]
 [3.050781 1.9375   1.332031]
 [3.288086 1.96875  1.333008]
 [3.466064 1.984375 1.333252]
 [3.599548 1.992188 1.333313]
 [3.699661 1.996